[package]
name = "engineering-plotter"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
clap = "2.33"
num-complex = "0.4"
plotters = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
chrono = "0.4.39"